### ISSUE TITLE
Getting error while running the test.py

### ISSUE THREAD

**Issue by saawan** [Mysterico/sentiment_analysis#8]
I am getting the following error when I run the test.py 
kindly give me some pointers.

root@tensorflow-1-vm:~/sentiment_analysis# python3 test/test.py
2020-03-25 22:45:12.735559: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-03-25 22:45:14.055479: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-25 22:45:14.057308: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
Traceback (most recent call last):
  File "test/test.py", line 2, in <module>
    from sentiment import SentimentAnalysis
  File "/usr/local/lib/python3.5/dist-packages/sentiment_analysis-0.1.5-py3.5.egg/sentiment/__init__.py", line 9, in <module>
    from util.summarize import Summarize
ImportError: No module named 'util'

**Comment by saawan** [comment]
Additional details: I am running it on the GCP deep-learning VM instance created by https://cloud.google.com/ai-platform/deep-learning-vm/docs/tensorflow_start_instance

**Comment by saawan** [comment]
here is the output of my setup.py install

root@tensorflow-1-vm:~/sentiment_analysis# python3 setup.py install
running install
running bdist_egg
running egg_info
writing top-level names to sentiment_analysis.egg-info/top_level.txt
writing sentiment_analysis.egg-info/PKG-INFO
writing requirements to sentiment_analysis.egg-info/requires.txt
writing dependency_links to sentiment_analysis.egg-info/dependency_links.txt
reading manifest file 'sentiment_analysis.egg-info/SOURCES.txt'
writing manifest file 'sentiment_analysis.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/sentiment
copying build/lib/sentiment/__init__.py -> build/bdist.linux-x86_64/egg/sentiment
byte-compiling build/bdist.linux-x86_64/egg/sentiment/__init__.py to __init__.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying sentiment_analysis.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sentiment_analysis.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sentiment_analysis.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sentiment_analysis.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sentiment_analysis.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying sentiment_analysis.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/sentiment_analysis-0.1.5-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing sentiment_analysis-0.1.5-py3.5.egg
removing '/usr/local/lib/python3.5/dist-packages/sentiment_analysis-0.1.5-py3.5.egg' (and everything under it)
creating /usr/local/lib/python3.5/dist-packages/sentiment_analysis-0.1.5-py3.5.egg
Extracting sentiment_analysis-0.1.5-py3.5.egg to /usr/local/lib/python3.5/dist-packages
sentiment-analysis 0.1.5 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.5/dist-packages/sentiment_analysis-0.1.5-py3.5.egg
Processing dependencies for sentiment-analysis==0.1.5
Searching for langdetect==1.0.8
Best match: langdetect 1.0.8
Processing langdetect-1.0.8-py3.5.egg
langdetect 1.0.8 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/langdetect-1.0.8-py3.5.egg
Searching for nltk==3.4.5
Best match: nltk 3.4.5
Adding nltk 3.4.5 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for pandas==0.25.3
Best match: pandas 0.25.3
Adding pandas 0.25.3 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for numpy==1.16.0
Best match: numpy 1.16.0
Adding numpy 1.16.0 to easy-install.pth file
Installing f2py3 script to /usr/local/bin
Installing f2py script to /usr/local/bin
Installing f2py3.5 script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for tensorflow==2.2.0rc1
Best match: tensorflow 2.2.0rc1
Processing tensorflow-2.2.0rc1-py3.5-linux-x86_64.egg
tensorflow 2.2.0rc1 is already the active version in easy-install.pth
Installing tensorboard script to /usr/local/bin
Installing toco_from_protos script to /usr/local/bin
Installing toco script to /usr/local/bin
Installing tf_upgrade_v2 script to /usr/local/bin
Installing saved_model_cli script to /usr/local/bin
Installing estimator_ckpt_converter script to /usr/local/bin
Installing tflite_convert script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages/tensorflow-2.2.0rc1-py3.5-linux-x86_64.egg
Searching for lexrankr==0.1.6
Best match: lexrankr 0.1.6
Processing lexrankr-0.1.6-py3.5.egg
lexrankr 0.1.6 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/lexrankr-0.1.6-py3.5.egg
Searching for konlpy==0.5.2
Best match: konlpy 0.5.2
Processing konlpy-0.5.2-py3.5.egg
konlpy 0.5.2 is already the active version in easy-install.pth
Installing stream_twitter script to /usr/local/bin
Installing stream_daum script to /usr/local/bin
Installing stream_naver script to /usr/local/bin
Installing stream_google script to /usr/local/bin
Installing stream_dcinside script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages/konlpy-0.5.2-py3.5.egg
Searching for six==1.14.0
Best match: six 1.14.0
Adding six 1.14.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for singledispatch==3.4.0.3
Best match: singledispatch 3.4.0.3
Processing singledispatch-3.4.0.3-py3.5.egg
singledispatch 3.4.0.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/singledispatch-3.4.0.3-py3.5.egg
Searching for pytz==2019.3
Best match: pytz 2019.3
Adding pytz 2019.3 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for python-dateutil==2.8.1
Best match: python-dateutil 2.8.1
Adding python-dateutil 2.8.1 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for wrapt==1.11.2
Best match: wrapt 1.11.2
Adding wrapt 1.11.2 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for wheel==0.29.0
Best match: wheel 0.29.0
Adding wheel 0.29.0 to easy-install.pth file
Installing wheel script to /usr/local/bin

Using /usr/lib/python3/dist-packages
Searching for termcolor==1.1.0
Best match: termcolor 1.1.0
Adding termcolor 1.1.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for tensorflow-estimator==2.2.0rc0
Best match: tensorflow-estimator 2.2.0rc0
Processing tensorflow_estimator-2.2.0rc0-py3.5.egg
tensorflow-estimator 2.2.0rc0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/tensorflow_estimator-2.2.0rc0-py3.5.egg
Searching for tensorboard==2.1.0
Best match: tensorboard 2.1.0
Adding tensorboard 2.1.0 to easy-install.pth file
Installing tensorboard script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for scipy==1.4.1
Best match: scipy 1.4.1
Processing scipy-1.4.1-py3.5-linux-x86_64.egg
Removing scipy 1.1.0 from easy-install.pth file
scipy 1.4.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/scipy-1.4.1-py3.5-linux-x86_64.egg
Searching for protobuf==3.11.2
Best match: protobuf 3.11.2
Adding protobuf 3.11.2 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for opt-einsum==3.1.0
Best match: opt-einsum 3.1.0
Adding opt-einsum 3.1.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for Keras-Preprocessing==1.1.0
Best match: Keras-Preprocessing 1.1.0
Adding Keras-Preprocessing 1.1.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for h5py==2.10.0
Best match: h5py 2.10.0
Adding h5py 2.10.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for grpcio==1.26.0
Best match: grpcio 1.26.0
Adding grpcio 1.26.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for google-pasta==0.1.8
Best match: google-pasta 0.1.8
Adding google-pasta 0.1.8 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for gast==0.3.3
Best match: gast 0.3.3
Processing gast-0.3.3-py3.5.egg
gast 0.3.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/gast-0.3.3-py3.5.egg
Searching for astunparse==1.6.3
Best match: astunparse 1.6.3
Processing astunparse-1.6.3-py3.5.egg
astunparse 1.6.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/astunparse-1.6.3-py3.5.egg
Searching for absl-py==0.9.0
Best match: absl-py 0.9.0
Adding absl-py 0.9.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for JPype1-py3==0.5.5.4
Best match: JPype1-py3 0.5.5.4
Processing JPype1_py3-0.5.5.4-py3.5-linux-x86_64.egg
JPype1-py3 0.5.5.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/JPype1_py3-0.5.5.4-py3.5-linux-x86_64.egg
Searching for sklearn==0.0
Best match: sklearn 0.0
Processing sklearn-0.0-py3.5.egg
sklearn 0.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/sklearn-0.0-py3.5.egg
Searching for gensim==3.8.1
Best match: gensim 3.8.1
Processing gensim-3.8.1-py3.5-linux-x86_64.egg
gensim 3.8.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/gensim-3.8.1-py3.5-linux-x86_64.egg
Searching for networkx==2.4
Best match: networkx 2.4
Adding networkx 2.4 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for setuptools==45.1.0
Best match: setuptools 45.1.0
Adding setuptools 45.1.0 to easy-install.pth file
Installing easy_install-3.8 script to /usr/local/bin
Installing easy_install script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for tweepy==3.8.0
Best match: tweepy 3.8.0
Processing tweepy-3.8.0-py3.5.egg
tweepy 3.8.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/tweepy-3.8.0-py3.5.egg
Searching for lxml==4.4.2
Best match: lxml 4.4.2
Adding lxml 4.4.2 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for colorama==0.4.3
Best match: colorama 0.4.3
Adding colorama 0.4.3 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for beautifulsoup4==4.6.0
Best match: beautifulsoup4 4.6.0
Processing beautifulsoup4-4.6.0-py3.5.egg
beautifulsoup4 4.6.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/beautifulsoup4-4.6.0-py3.5.egg
Searching for JPype1==0.7.2
Best match: JPype1 0.7.2
Processing JPype1-0.7.2-py3.5-linux-x86_64.egg
JPype1 0.7.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/JPype1-0.7.2-py3.5-linux-x86_64.egg
Searching for google-auth-oauthlib==0.4.1
Best match: google-auth-oauthlib 0.4.1
Adding google-auth-oauthlib 0.4.1 to easy-install.pth file
Installing google-oauthlib-tool script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for requests==2.22.0
Best match: requests 2.22.0
Adding requests 2.22.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for Markdown==3.1.1
Best match: Markdown 3.1.1
Adding Markdown 3.1.1 to easy-install.pth file
Installing markdown_py script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for Werkzeug==0.16.1
Best match: Werkzeug 0.16.1
Adding Werkzeug 0.16.1 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for google-auth==1.11.0
Best match: google-auth 1.11.0
Adding google-auth 1.11.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for scikit-learn==0.19.2
Best match: scikit-learn 0.19.2
Adding scikit-learn 0.19.2 to easy-install.pth file

Using /usr/local/lib/python3.5/site-packages
Searching for smart-open==1.10.0
Best match: smart-open 1.10.0
Processing smart_open-1.10.0-py3.5.egg
smart-open 1.10.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/smart_open-1.10.0-py3.5.egg
Searching for decorator==4.4.1
Best match: decorator 4.4.1
Adding decorator 4.4.1 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for requests-oauthlib==1.3.0
Best match: requests-oauthlib 1.3.0
Adding requests-oauthlib 1.3.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for PySocks==1.7.1
Best match: PySocks 1.7.1
Processing PySocks-1.7.1-py3.5.egg
PySocks 1.7.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/PySocks-1.7.1-py3.5.egg
Searching for certifi==2019.11.28
Best match: certifi 2019.11.28
Adding certifi 2019.11.28 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for idna==2.8
Best match: idna 2.8
Adding idna 2.8 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for urllib3==1.24.2
Best match: urllib3 1.24.2
Adding urllib3 1.24.2 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for pyasn1-modules==0.2.8
Best match: pyasn1-modules 0.2.8
Adding pyasn1-modules 0.2.8 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for cachetools==4.0.0
Best match: cachetools 4.0.0
Adding cachetools 4.0.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for rsa==4.0
Best match: rsa 4.0
Adding rsa 4.0 to easy-install.pth file
Installing pyrsa-keygen script to /usr/local/bin
Installing pyrsa-priv2pub script to /usr/local/bin
Installing pyrsa-sign script to /usr/local/bin
Installing pyrsa-verify script to /usr/local/bin
Installing pyrsa-decrypt script to /usr/local/bin
Installing pyrsa-encrypt script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for pydaal==2019.0.0.20180713
Best match: pydaal 2019.0.0.20180713
Adding pydaal 2019.0.0.20180713 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for intel-scipy==1.1.0
Best match: intel-scipy 1.1.0
Adding intel-scipy 1.1.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for google-cloud-storage==1.25.0
Best match: google-cloud-storage 1.25.0
Adding google-cloud-storage 1.25.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for boto3==1.12.29
Best match: boto3 1.12.29
Processing boto3-1.12.29-py3.5.egg
boto3 1.12.29 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/boto3-1.12.29-py3.5.egg
Searching for oauthlib==3.1.0
Best match: oauthlib 3.1.0
Adding oauthlib 3.1.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for pyasn1==0.4.8
Best match: pyasn1 0.4.8
Adding pyasn1 0.4.8 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for tbb4py==2019.0
Best match: tbb4py 2019.0
Adding tbb4py 2019.0 to easy-install.pth file
Installing python-tbb script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for daal==2019.0
Best match: daal 2019.0
Adding daal 2019.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for intel-numpy==1.15.1
Best match: intel-numpy 1.15.1
Adding intel-numpy 1.15.1 to easy-install.pth file
Installing f2py script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages
Searching for google-resumable-media==0.5.0
Best match: google-resumable-media 0.5.0
Adding google-resumable-media 0.5.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for google-cloud-core==1.2.0
Best match: google-cloud-core 1.2.0
Adding google-cloud-core 1.2.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for s3transfer==0.3.3
Best match: s3transfer 0.3.3
Processing s3transfer-0.3.3-py3.5.egg
s3transfer 0.3.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/s3transfer-0.3.3-py3.5.egg
Searching for jmespath==0.9.5
Best match: jmespath 0.9.5
Processing jmespath-0.9.5-py3.5.egg
jmespath 0.9.5 is already the active version in easy-install.pth
Installing jp.py script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages/jmespath-0.9.5-py3.5.egg
Searching for botocore==1.15.29
Best match: botocore 1.15.29
Processing botocore-1.15.29-py3.5.egg
botocore 1.15.29 is already the active version in easy-install.pth

Using /usr/local/lib/python3.5/dist-packages/botocore-1.15.29-py3.5.egg
Searching for tbb==2019.0
Best match: tbb 2019.0
Adding tbb 2019.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for mkl==2019.0
Best match: mkl 2019.0
Adding mkl 2019.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for icc-rt==2020.0.133
Best match: icc-rt 2020.0.133
Adding icc-rt 2020.0.133 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for mkl-random==1.0.1.1
Best match: mkl-random 1.0.1.1
Adding mkl-random 1.0.1.1 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for mkl-fft==1.0.6
Best match: mkl-fft 1.0.6
Adding mkl-fft 1.0.6 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for google-api-core==1.16.0
Best match: google-api-core 1.16.0
Adding google-api-core 1.16.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for docutils==0.15.2
Best match: docutils 0.15.2
Processing docutils-0.15.2-py3.5.egg
docutils 0.15.2 is already the active version in easy-install.pth
Installing rst2html4.py script to /usr/local/bin
Installing rst2xetex.py script to /usr/local/bin
Installing rst2man.py script to /usr/local/bin
Installing rstpep2html.py script to /usr/local/bin
Installing rst2s5.py script to /usr/local/bin
Installing rst2pseudoxml.py script to /usr/local/bin
Installing rst2html5.py script to /usr/local/bin
Installing rst2odt.py script to /usr/local/bin
Installing rst2html.py script to /usr/local/bin
Installing rst2latex.py script to /usr/local/bin
Installing rst2xml.py script to /usr/local/bin
Installing rst2odt_prepstyles.py script to /usr/local/bin

Using /usr/local/lib/python3.5/dist-packages/docutils-0.15.2-py3.5.egg
Searching for intel-openmp==2020.0.133
Best match: intel-openmp 2020.0.133
Adding intel-openmp 2020.0.133 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Searching for googleapis-common-protos==1.51.0
Best match: googleapis-common-protos 1.51.0
Adding googleapis-common-protos 1.51.0 to easy-install.pth file

Using /usr/local/lib/python3.5/dist-packages
Finished processing dependencies for sentiment-analysis==0.1.5
root@tensorflow-1-vm:~/sentiment_analysis

**Comment by saawan** [comment]
i am able to pass the above problem and am at the following error.  any help is appreciated.



root@instance-1:~/sentiment_analysis# python3 ./test1.py
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "./test1.py", line 1, in <module>
    from sentiment import SentimentAnalysis
  File "/root/sentiment_analysis/sentiment/__init__.py", line 11, in <module>
    okt = Okt()
  File "/usr/local/lib/python3.6/dist-packages/konlpy/tag/_okt.py", line 91, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "/usr/local/lib/python3.6/dist-packages/konlpy/jvm.py", line 67, in init_jvm
    convertStrings=True)
TypeError: startJVM() got an unexpected keyword argument 'convertStrings'
root@instance-1:~/sentiment_analysis#

**Comment by saawan** [comment]
this the latest error i am getting.

```
root@instance-1:~/sentiment_analysis# python3 ./test1.py
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "./test1.py", line 1, in <module>
    from sentiment import SentimentAnalysis
  File "/root/sentiment_analysis/sentiment/__init__.py", line 11, in <module>
    okt = Okt()
  File "/usr/local/lib/python3.6/dist-packages/konlpy/tag/_okt.py", line 91, in __init__
    jvm.init_jvm(jvmpath, max_heap_size)
  File "/usr/local/lib/python3.6/dist-packages/konlpy/jvm.py", line 67, in init_jvm
    convertStrings=True)
TypeError: startJVM() got an unexpected keyword argument 'convertStrings'
root@instance-1:~/sentiment_analysis#

```
